version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: maven_rocket
      POSTGRES_PASSWORD: maven_rocket
      POSTGRES_DB: maven_rocket
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro